### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by Ziklepmna** [hebaishi/linter-gcc#11] opened 2015-10-30 03:36 UTC
Hello, I´m new to Atom and I´m loving it so far but I can´t get linter working with C, it always says "No issues", I dont know if it´s this package linter-gcc or linter itself, I´ve googled everywhere but I can´t find the solution.

Any help is much appreciated

Thanks!

**Comment by hebaishi** [comment] 2015-10-30 10:42
Hello. Could you please do the following: open the javascript console in atom, and look for the linter-gcc messages. It prints all its command-line parameters to the console, so the first thing to do is to copy those parameters and try to run them directly in the command-line.

**Comment by Ziklepmna** [comment] 2015-10-30 13:39
I am so sorry but I don't know how to do that, I toggled developer tools but I don't know what to do from there, can you guide me through the process if it isn't much trouble?
Thanks again

**Comment by hebaishi** [comment] 2015-10-30 13:46
Of course. With 'developer tools' on, you should see a sidebar, and at the bottom of this sidebar you'll see a button that says 'console'. Click it to view the console. Then go back to your C/C++ source file, and press Ctrl+S to save and trigger the linter. When you do this, you'll see something like this appear in the console:
```
/usr/bin/g++
["-Wall", "-std=c++0x", "-fmax-errors=0",
"-I/home/husam/.atom/packages/linter-gcc", "/tmp/sample.cpp"]
```
These are your command-line parameters. The first is the g++ binary, and the rest is the parameters given to g++. So, if we consider the example above, my full command would be:
```
/usr/bin/g++ -Wall -std=c++0x -fmax-errors=0 -I/home/husam/.atom/packages/linter-gcc /tmp/sample.cpp
```
You need to reconstruct your command in this way and run it in your terminal/command prompt to find out what g++/gcc is reporting.

**Comment by Ziklepmna** [comment] 2015-10-30 13:57
Okay, I got this:

/usr/bin/g++
main.js:149 ["-Wall", "-fmax-errors=0", "C:\Users\Nacho-PC2\Documents\TP FINAL.cpp"]

Then I changed it to this:

/usr/bin/g++main.js:149 -Wall, -fmax-errors=0, C:\Users\Nacho-PC2\Documents\TP FINAL.cpp

I have Windows, so I assume you mean put that in the cmd, I did that from the .atom directory (don´t know if this is right) and it says "The system cannot find the path specified."

I surely must be doing something wrong.
Damn, I hate being new to stuff :P

**Comment by hebaishi** [comment] 2015-10-30 14:14
Ok there are a few problems here:
1. You need to remove the ```main.js:149``` from your command. You also need to remove all the commas.
2. It looks like you are trying to run /usr/bin/g++. Windows does not have a /usr/bin so this probably won't work on windows. You need to go into the linter-gcc configuration page and put the full location of the g++ binary in there. If you don't have one, I suggest you look at installing something something like mingw on windows.
3. Secondly, you have a space in your file path. This will cause problems because a file path with spaces will cause gcc/g++ to parse part of your file path as a parameter, which it will complain about. To get around this problem, either change your file path and replace ALL spaces with underscores, or enclose the path within double quotes.

**Comment by Ziklepmna** [comment] 2015-10-30 14:29
Okay
1. Done:

/usr/bin/g++ -Wall -fmax-errors=0 C:\Users\Nacho-PC2\Documents\TPFINAL.cpp

2. I already have MinGW, so I guess the path that I´m looking for is:

C:\MinGW\bin\g++.exe

Right?

Also, by configuration page, you mean the linter-gcc/lib/main.js? Because I found this in there:

  execPath: {
      type: "string",
      default: "/usr/bin/g++"

Maybe this is the problem?

3. Done, see 1.

**Comment by hebaishi** [comment] 2015-10-30 14:32
No. That is not it. In the menu bar, click Packages > Settings view. Then click packages on the left and select linter-gcc. There you will find the linter-gcc settings. The first one is the executable path. Set that to your executable path, in your case ```C:\MinGW\g++.exe```.

**Comment by Ziklepmna** [comment] 2015-10-30 14:39
Okay, you left out the bin folder :P
But it´s working now, but the lint on the fly isn´t, I have to save the file for linter to show me the errors, any workaround this?

**Comment by hebaishi** [comment] 2015-10-30 14:45
No, this is deliberate. The reason it works like this is because C/C++ linting can be quite computationally intensive, so linting on-the-fly can cause high CPU load, especially with large files/projects.

**Comment by Ziklepmna** [comment] 2015-10-30 14:48
Ohhhhh, got it, well it's working perfectly now! Thanks a lot! :)

If it's no bother, I've got another question about Atom, but it's not related to linter-gcc, is there a private message button somewhere?

**Comment by hebaishi** [comment] 2015-10-30 14:52
Yes, that's fine. You can send me a message on twitter. My handle is hebaishi_husam. I'm closing this issue.

**Comment by rviertel2** [comment] 2016-07-12 17:30
Hi hebaishi,

I am trying to follow the instructions here to get linter-gcc working in windows and I am not having success. No output displays in the console when I save

**Comment by hebaishi** [comment] 2016-07-13 10:54
Hello. I'm gonna upload a guide for Windows users today because it seems a large number of users have this problem.

What you need to do is:
1. Set the linter-gcc executable path to `g++.exe` or `gcc.exe`
2. Add your MinGW bin to the system path by following the instructions [here](https://java.com/en/download/help/path.xml). Note that you need to add the MinGW bin path to the end. So if your PATH variable reads `C:\Windows\`, and your MinGW bin path is `C:\MinGW\bin`, your new PATH variable should read `C:\Windows\;C:\MinGW\bin`. Note the use of the semicolon separator.

Once you have made this change, linter-gcc should work.

**Comment by rviertel2** [comment] 2016-07-13 14:45
Thanks for the response. I did change the executable path to C:\MinGW\bin\g++.exe and also added C:\MinGW\bin to both the path system and user variables. I still don't see anything show up for linter-gcc in the console when I save.

**Comment by hebaishi** [comment] 2016-07-13 15:08
Hello. Your linter-gcc executable path should be set to `g++.exe`, **NOT** `C:\MinGW\bin\g++.exe`. This is because windows needs to find `g++.exe` in your system path. Also, once you have changed your system PATH in the system properties, you might need to restart Atom for the change to take effect.

**Comment by rviertel2** [comment] 2016-07-13 16:06
great thank you for your reply. It is working now

**Closed** 2016-07-14 09:34 UTC

**Comment by charozard** [comment] 2016-07-29 17:51
Hi hebaishi,
I'm sorry to bring this back up again but I've encountered a similar problem which appears persistent despite following instructions above. Linter is failing to find a number of standard c++ libraries including string and iostream, though using g++ to compile the same files in terminal works just fine. Do you have any suggestions on remedying this issue?  Would the "GCC include paths" setting be the place to look? If so, which path ought I include?

**Comment by KarateBrot** [comment] 2017-04-15 20:29
Same for me. I followed the instructions. I can compile without errors in Atom but I still get the linter error: 
 GCC  |  "iostream: No such file or directory"

**Comment by AliAytacAyhan** [comment] 2017-07-27 21:40
how to know the path which linter has installed ?

**Comment by bqUAB** [comment] 2018-03-09 17:45
I can confirm that the fix works but after various unsuccessful tries I found my solution for Windows 7.
Follow @hebaishi instructions about the installation of Cygwin and setting the PATH variable.
Test PATH by opening a new CMD and typing `gcc –v`
**Close Atom and GitHub Desktop**
Reopen and test if it works now.

**Comment by GagahGK** [comment] 2018-03-22 07:14
Hi i'm sorry if this might annoy you
i just updated my plugin from atom before i updated my packages everything works fine
but after the update my linter stopped working nothing shows up anymore.
i'm using TDMGCC with the system variable Path set to 
`C:\Windows;C:\TDM-GCC-64\bin`
and set my GCC Executable path  to gcc.exe
but there's nothing shows up still
here's my console screenshot 
![capture](https://user-images.githubusercontent.com/20636513/37756209-377d7376-2ddb-11e8-978f-2d6aed2466d9.PNG)

what should i do ??, thankyou ...
