### ISSUE TITLE
RangeError: invalid string length

### ISSUE THREAD

**Issue by CodingAnarchy** [hebaishi/linter-gcc#28] opened 2016-02-09 02:06 UTC
Trying to save a `*.hpp` file and getting this error every time:

```
RangeError: Invalid string length
    at Object.stringify (native)
    at /Users/vision/.atom/packages/linter/lib/validate.coffee:53:25
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/Users/vision/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (/Users/vision/.atom/packages/linter/lib/message-registry.js:36:16)
    at /Users/vision/.atom/packages/linter/lib/linter.coffee:35:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/vision/.atom/packages/linter/lib/indie-registry.js:27:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Indie.setMessages (/Users/vision/.atom/packages/linter/lib/indie.js:15:18)
    at /Users/vision/.atom/packages/linter-gcc/lib/main.js:75:35
```

**Comment by hebaishi** [comment] 2016-02-09 02:16
Could you open the developer console with ```Ctrl+Shift+I```, copy the linter-gcc command, paste it into a terminal, run it, and post the output here?

**Comment by CodingAnarchy** [comment] 2016-02-11 04:18
Command output as requested:

`21:10:23 ~ >/usr/bin/g++ -c -Wall -std=c++11 -fmax-errors=0 /Users/vision/git/sim/lib/rocket.hpp
clang: warning: argument unused during compilation: '-fmax-errors=0'`

The error has also become intermittent, but I can change the file by just adding or removing an empty line and resaving and it may or may not happen again.

**Comment by CodingAnarchy** [comment] 2016-02-11 04:20
Restarting Atom also makes the error go away for a while, but it comes back after working for some period of time.

**Comment by hebaishi** [comment] 2016-02-11 17:08
I am concerned that your code is generating an error message that is just too long for linter to handle, a template error perhaps? Are you happy to post a sample of your C++ code so I can test it?

**Comment by Arignir** [comment] 2016-02-11 17:12
Same bug here, quite often :/

I got it with C code, not C++. And gcc isn't showing any error while compiling the file with the same command-line than linter-gcc.

**Comment by hebaishi** [comment] 2016-02-11 17:20
Ok. Let me try to reproduce the error and I will post a fix asap.

**Comment by hebaishi** [comment] 2016-02-11 17:21
Could someone give me a code sample that's causing the error?

**Comment by Arignir** [comment] 2016-02-11 17:25
When i have the error, reopening atom is usually enough to not having it again. So giving you a code that's causing the error will not be helpfull, as it will not cause the error on your side.

**Comment by hebaishi** [comment] 2016-02-11 17:32
This is very strange. I thought it was related to the error messages being very long, but it looks like that's not the case. I've deliberately linted source files that generate long error messages and everything works fine.

**Comment by Arignir** [comment] 2016-02-12 18:44
Having some news : when the "invalid string length" bug occurs, the errors pops every time i'm saving a file **even if it's not the file that caused the error**, and even if the file doesn't have any error.

**Comment by patrick-armitage** [comment] 2016-02-13 20:14
I'm having the same issue, any update on this?  It only started to occur after I upgraded atom to 1.5.3.  I've also kept up to date on linter-gcc, and it started breaking just today, so it must have been in a recent update that it started happening.

**Comment by XSmile2008** [comment] 2016-02-14 20:00
I have the same problem. After few hours of code writing i got long error. New errors come when i press Command-S to save(and lint) project. After I relaunch Atom, no errors, but after some time I have same errors. I have no errors if I disable or remove linter-gcc. 
My project:
https://github.com/XSmile2008/BigTrackArduino

**Comment by Arignir** [comment] 2016-02-26 13:57
I got the error 4 times in a hour now, it's very frustrating :s 

Is there a solution yet ?

**Comment by hebaishi** [comment] 2016-02-26 14:10
Hello all. I think I have identified the problem. Need to play some more to make sure it's fixed. The issue seems to be that atom reports the settings tab as an 'editor' as well. I need to make sure that linter-gcc doesn't try to lint it when that happens.

**Comment by hebaishi** [comment] 2016-02-26 16:24
Ok it seems the editor problem is secondary. The main issue is that linter stringifies its messages using ```JSON.stringify``` in the latest release [here](https://github.com/atom-community/linter/blob/35847e4c4893f264861967207570cc51c9ccdabb/lib/validate.coffee). This problem is not present in the latest commit, however, so all we need is for the latest commit to be published as a release.

@steelbrain could you help us here? Are you planning on publishing a new release soon?

**Comment by steelbrain** [comment] 2016-02-26 16:26
I am planning on publishing a new release soon but the workaround should work well for you, the only penalty should be performance and even that won't be anything major, worst case scenario you miss a frame which isn't too bad for a workaround IMHO

**Comment by hebaishi** [comment] 2016-02-26 17:04
Sounds good. Workaround details:
* Open Atom's package manager, find the ```linter``` package
* Click Settings, then View Code
* Open the file ```lib/validate.coffee```
* Goto line 53:
```javascript
result.key = JSON.stringify(result)
```
* Add the following line immediately before it:
```javascript
result.key = null
```
* Save the file, and restart Atom.

Let me know if the workaround fixes the problem. Once the new version of linter is released, this issue will be fixed.

**Comment by steelbrain** [comment] 2016-02-26 17:10
This is not really the workaround, the workaround I suggested should be done by the providers and not the end users themselves, I suggested `JSON.parse(JSON.stringify(messages))`

Another approach to solve this would be to solve only the text instead of message objects and then do
```js
const messages = []
for (const message of this.errors) {
  messages.push({type: 'Error', text: message.text, range: message.range})
}
```

**Comment by hebaishi** [comment] 2016-02-26 17:21
@steelbrain but the issue is that the base linter does the stringification, not linter-gcc. linter-gcc simply passes the messages to linter. Any ideas as to how to work around this problem?

**Comment by steelbrain** [comment] 2016-02-26 17:23
Change [`this`](https://github.com/hebaishi/linter-gcc/blob/8128f15181b4bf515c1c9f46bc4848da356fc289/lib/main.js#L144) line to `module.exports.linter_gcc.setMessages(JSON.parse(JSON.stringify(require("./utility").flattenHash(module.exports.messages))));`

**Comment by hebaishi** [comment] 2016-02-27 01:48
@steelbrain thanks for the help. The workaround has been implemented. Please update linter-gcc.

**Comment by Arignir** [comment] 2016-02-27 10:34
A friend of mine just got the error again :s He's on 0.6.8 update !

**Comment by hebaishi** [comment] 2016-02-27 11:33
Has he restarted Atom? A restart is necessary to reload the package.

**Comment by hebaishi** [comment] 2016-02-27 11:39
I have run tests with the [BigTrackArduino](https://github.com/XSmile2008/BigTrackArduino) project, and the issue before was that one of the message objects passed to ```linter``` would grow in size if you opened more than one file. This could continue until the object was too big for node to handle. Now, the size of all objects remains the same no matter how many files you open/save.

**Comment by Arignir** [comment] 2016-02-27 12:54
Ah maybe not, he can't remember ! Indeed, i don't have the error now ^^

Thanks for the patch !

**Comment by hebaishi** [comment] 2016-02-27 13:28
No problem. Glad it's all working again. I will update linter-gcc again once linter has been updated.

**Closed by hebaishi** 2016-02-27 13:28 UTC
Labels: bug
